# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: BikePath
description: >
  BikePath helps bikes and scooter sharing providers decide where to put their bikes and scooters.
owner: BikePath # or company name
first_published: 2020 # if migrating another site, the year of your first publish
email: dhruv@bikepath.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bikepath.io" # the base hostname & protocol for your site, e.g. http://example.com
social:
  twitter: https://twitter.com/bikepathio
  # github: https://github.com/<username>
  
  email: mailto:founders@bikepath.io
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>

# Build settings
markdown: kramdown
#sass:
#  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
